// controllers/categoryController.js
import Category from '../models/Category.js';
import Product from '../models/productModel.js';
import mongoose from 'mongoose';
import slugify from 'slugify';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import sharp from 'sharp';
import { GoogleGenAI } from '@google/genai';
import axios from 'axios';
import {
  ValidationError,
  NotFoundError,
  ConflictError,
  DatabaseError,
  BusinessLogicError
} from '../utils/errors.js';
import { uploadFileToR2, deleteFileFromR2 } from '../services/r2Service.js';

// ===== DEBUG: CATEGORY CONTROLLER =====
console.log('🔵 ===== CATEGORY CONTROLLER DEBUG =====');
console.log('🔵 GEMINI_API_KEY exists:', !!process.env.GEMINI_API_KEY);
console.log('🔵 GEMINI_API_KEY length:', process.env.GEMINI_API_KEY?.length);
console.log('🔵 R2 Configuration:', {
  accountId: process.env.R2_ACCOUNT_ID ? '✅ Set' : '❌ Missing',
  bucket: process.env.R2_BUCKET_NAME || '❌ Missing',
  endpoint: process.env.R2_ENDPOINT ? '✅ Set' : '❌ Missing',
});
console.log('🔵 ========================================');

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ✅ Initialize Gemini API
// ✅ Generate description using Gemini API - EXPORT THIS FUNCTION
export const generateDescriptionWithGemini = async (categoryName) => {
    const genAI = new GoogleGenAI({
    
    apiKey: process.env.GEMINI_API_KEY,
    httpOptions: {
        apiVersion: 'v1'
    }

});
  try {
    console.log('🤖 Generating category content with Gemini...');
    console.log(`📂 Category: ${categoryName}`);

    if (!process.env.GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY is missing');
    }

    console.log('🔵 INSIDE FUNCTION - API Key exists:', !!process.env.GEMINI_API_KEY);
    console.log('🔵 INSIDE FUNCTION - API Key length:', process.env.GEMINI_API_KEY?.length);

    const interaction = await genAI.interactions.create({
      model: 'gemini-3.6-flash',

      input: `
Generate SEO-optimized content for this e-commerce category.

Category:
${categoryName}

Return ONLY valid JSON using exactly this structure:

{
  "description": "100-150 word category description",
  "metaTitle": "50-60 character SEO title",
  "metaDescription": "150-160 character SEO description",
  "metaKeywords": [
    "keyword 1",
    "keyword 2",
    "keyword 3",
    "keyword 4",
    "keyword 5"
  ]
}

Description requirements:

- Write a natural, human-sounding e-commerce category description.
- The description must be between 100 and 150 words.
- Do NOT start with "Discover".
- Do NOT start with "Explore".
- Do NOT start with "Experience".
- Do NOT start with "Introducing".
- Do NOT start with "Upgrade".
- Do NOT start with "Unlock".
- Do NOT start with "Transform".
- Do NOT start with "Elevate".
- Do NOT start with "Shop our".
- Do NOT use generic AI marketing openings.
- Start directly with the category name, product type, or a specific customer benefit.
- The first sentence should immediately explain what the category contains or what customers can expect.
- Use varied sentence structures.
- Avoid repetitive phrases between different categories.
- Make the content useful for customers, not just promotional.
- Naturally include relevant keywords.
- Do not keyword-stuff.
- Do not mention that the content was generated by AI.

SEO requirements:

- Meta title should be concise and SEO-friendly.
- Meta title should ideally be 50-60 characters.
- Meta description should ideally be 150-160 characters.
- Meta description should clearly explain the category and encourage clicks.
- Meta keywords should contain 5-10 relevant search terms.
- Keywords must be relevant to the category.

Important:

- No markdown.
- No code blocks.
- No explanations outside the JSON.
- Return valid JSON only.
` 
    });

    const text = interaction.output_text;

    console.log('✅ Gemini response received');
    console.log('📝 Response:', text);

    if (!text) {
      throw new Error('Gemini returned an empty response');
    }

    // Clean Gemini response
    let cleanText = text
      .replace(/```json/gi, '')
      .replace(/```/g, '')
      .trim();

    // Extract JSON object if Gemini adds extra text
    const start = cleanText.indexOf('{');
    const end = cleanText.lastIndexOf('}');

    if (start === -1 || end === -1) {
      throw new Error('Gemini did not return valid JSON');
    }

    cleanText = cleanText.substring(start, end + 1);

    const parsed = JSON.parse(cleanText);

    console.log('✅ Category content parsed successfully');

    return {
      description: parsed.description || '',

      metaTitle:
        parsed.metaTitle ||
        categoryName,

      metaDescription:
        parsed.metaDescription ||
        `Shop the best ${categoryName} at great prices.`,

      metaKeywords:
        Array.isArray(parsed.metaKeywords)
          ? parsed.metaKeywords
          : []
    };

  } catch (error) {
    console.error('❌ Gemini API error:', error);

    // ✅ Extract and show exact error
    let errorMessage = 'Gemini API failed';
    
    if (error.message) {
      errorMessage = error.message;
    }
    
    if (error.status) {
      errorMessage += ` (HTTP ${error.status})`;
    }
    
    if (error.errorDetails) {
      errorMessage += ` - ${JSON.stringify(error.errorDetails)}`;
    }

    throw new Error(errorMessage);
  }
};

// ✅ Generate image using Pollinations.ai (UPDATED for R2)
// controllers/categoryController.js

// ✅ Generate image using Pollinations.ai - UPDATED folder path
export const generateImageWithPollinations = async (categoryName) => {
    try {
        const imagePrompt = `High quality professional product photography for ${categoryName} category, e-commerce style, clean white background, studio lighting, 4K, detailed`;
        const encodedPrompt = encodeURIComponent(imagePrompt);
        const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}`;
        
        console.log(`🖼️ Generating image for category: ${categoryName}`);
        
        const response = await axios({
            method: 'get',
            url: imageUrl,
            responseType: 'arraybuffer',
            timeout: 30000
        });

        const timestamp = Date.now();
        const random = Math.round(Math.random() * 1E9);
        const filename = `${timestamp}-${random}.webp`;
        
        // ✅ UPDATED: Upload to backend-images/categories
        const result = await uploadFileToR2(
            response.data, 
            filename, 
            'backend-images/categories',  // ← Changed from 'categories'
            'image/webp'
        );

        console.log(`✅ Category image uploaded to R2: ${result.url}`);
        return result.url;
        
    } catch (error) {
        console.error('❌ Error generating image with Pollinations:', error);
        return null;
    }
};

// ✅ Save uploaded file to R2 - UPDATED folder path
const saveUploadedFileToR2 = async (file) => {
    try {
        const buffer = await file.toBuffer();
        
        const timestamp = Date.now();
        const random = Math.round(Math.random() * 1E9);
        const filename = `${timestamp}-${random}.webp`;
        
        // ✅ UPDATED: Upload to backend-images/categories
        const result = await uploadFileToR2(buffer, filename, 'backend-images/categories', 'image/webp');
        
        console.log(`✅ File saved to R2: ${result.url}`);
        return result.url;
    } catch (error) {
        console.error('❌ Error saving file to R2:', error);
        return null;
    }
};



// ✅ Delete file from R2
const deleteFile = async (filePath) => {
    if (!filePath) return false;
    try {
        // Check if it's an R2 URL
        if (filePath.startsWith('http://') || filePath.startsWith('https://')) {
            console.log(`🗑️ Deleting from R2: ${filePath}`);
            const result = await deleteFileFromR2(filePath);
            return result.success;
        }
        
        // For backward compatibility - local file deletion
        const fullPath = path.join(process.cwd(), filePath);
        if (fs.existsSync(fullPath)) {
            fs.unlinkSync(fullPath);
            console.log(`✅ Deleted: ${filePath}`);
            return true;
        }
        return false;
    } catch (error) {
        console.error('❌ Error deleting file:', error);
        return false;
    }
};

// ✅ 1. CREATE CATEGORY
export const createCategory = async (req, reply) => {
    const { 
        name, 
        description, 
        parent, 
        status, 
        featured, 
        metaTitle, 
        metaDescription, 
        metaKeywords, 
        displayOrder,
        existingImagePath // ✅ Reuse image from preview
    } = req.body;

    if (!name || !name.trim()) {
        throw new ValidationError('Category name is required', {
            field: 'name',
            required: true
        });
    }

    const existingCategory = await Category.findOne({ name: name.trim() });
    if (existingCategory) {
        throw new ConflictError('Category with this name already exists', {
            name: name.trim()
        });
    }

    // ✅ Handle image - priority: uploaded file > existingImagePath (from preview) > null
    let imagePath = null;
    
    if (req.uploadedFile) {
        // User uploaded an image
        imagePath = await saveUploadedFileToR2(req.uploadedFile);
        console.log('📷 Using uploaded image (R2)');
    } else if (existingImagePath) {
        // ✅ Use the image from preview (no new generation)
        imagePath = existingImagePath;
        console.log('📷 Using existing preview image:', imagePath);
    } else {
        console.log('📷 No image provided');
    }

    const slug = slugify(name.trim(), { lower: true, strict: true });
    let finalSlug = slug;
    let counter = 1;
    while (await Category.findOne({ slug: finalSlug })) {
        finalSlug = `${slug}-${counter}`;
        counter++;
    }

    // ✅ Auto-generate description if not provided
    let finalDescription = description || '';
    let finalMetaTitle = metaTitle || '';
    let finalMetaDescription = metaDescription || '';
    let parsedMetaKeywords = [];

    if (!description && !metaTitle && !metaDescription && !metaKeywords) {
        console.log(`🔄 Generating content for category: ${name.trim()}`);
        const generated = await generateDescriptionWithGemini(name.trim());
        finalDescription = generated.description;
        finalMetaTitle = generated.metaTitle;
        finalMetaDescription = generated.metaDescription;
        parsedMetaKeywords = generated.metaKeywords;
    } else {
        // Parse metaKeywords if provided
        if (metaKeywords) {
            if (Array.isArray(metaKeywords)) {
                parsedMetaKeywords = metaKeywords;
            } else if (typeof metaKeywords === 'string') {
                parsedMetaKeywords = metaKeywords.split(',').map(k => k.trim()).filter(Boolean);
            }
        }
    }

    const category = new Category({
        name: name.trim(),
        slug: finalSlug,
        description: finalDescription,
        parent: parent || null,
        image: imagePath,
        status: status || 'active',
        featured: featured === 'true' || featured === true,
        metaTitle: finalMetaTitle || name.trim(),
        metaDescription: finalMetaDescription || `Shop the best ${name.trim()} at great prices.`,
        metaKeywords: parsedMetaKeywords,
        displayOrder: parseInt(displayOrder) || 0,
        createdBy: req.user.id
    });

    await category.save();

    reply.status(201).send({
        success: true,
        message: 'Category created successfully',
        data: category
    });
};

// ✅ 2. GET ALL CATEGORIES
export const getAllCategories = async (req, reply) => {
    const { status, featured, parent } = req.query;
    const filter = {};
    if (status) filter.status = status;
    if (featured === 'true') filter.featured = true;
    if (parent) filter.parent = parent === 'null' ? null : parent;

    const categories = await Category.find(filter)
        .populate('parent', 'name slug')
        .sort('displayOrder name');

    reply.status(200).send({
        success: true,
        count: categories.length,
        data: categories
    });
};

// ✅ 3. GET ACTIVE CATEGORIES
export const getActiveCategories = async (req, reply) => {
    const categories = await Category.find({ status: 'active' })
        .populate('parent', 'name slug')
        .sort('displayOrder name');

    reply.status(200).send({
        success: true,
        count: categories.length,
        data: categories
    });
};

// ✅ 4. GET CATEGORY BY ID
export const getCategoryById = async (req, reply) => {
    const { id } = req.params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
        throw new ValidationError('Invalid category ID', {
            field: 'id',
            received: id
        });
    }

    const category = await Category.findById(id)
        .populate('parent', 'name slug')
        .populate('subcategories', 'name slug image');

    if (!category) {
        throw new NotFoundError('Category', { id });
    }

    reply.status(200).send({
        success: true,
        data: category
    });
};

// ✅ 5. UPDATE CATEGORY
export const updateCategory = async (req, reply) => {
    const { id } = req.params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
        throw new ValidationError('Invalid category ID', {
            field: 'id',
            received: id
        });
    }

    const category = await Category.findById(id);
    if (!category) {
        throw new NotFoundError('Category', { id });
    }

    const { 
        name, 
        description, 
        parent, 
        status, 
        featured, 
        metaTitle, 
        metaDescription, 
        metaKeywords, 
        displayOrder, 
        deleteImage,
        existingImagePath // ✅ Reuse image from preview
    } = req.body;

    // ✅ Handle image deletion
    if (deleteImage === 'true' || deleteImage === true) {
        if (category.image) {
            await deleteFile(category.image);
            category.image = null;
        }
    }

    // ✅ Handle new image (replaces old) - priority: uploaded > existingImagePath
    if (req.uploadedFile) {
        // User uploaded a new image
        if (category.image) {
            await deleteFile(category.image);
        }
        category.image = await saveUploadedFileToR2(req.uploadedFile);
        console.log('📷 Using uploaded image (R2)');
    } else if (existingImagePath) {
        // ✅ Use the image from preview (no new generation)
        if (category.image) {
            await deleteFile(category.image);
        }
        category.image = existingImagePath;
        console.log('📷 Using existing preview image:', existingImagePath);
    }

    // ✅ Update fields with auto-generation if name changes and fields are empty
    if (name && name.trim()) {
        category.name = name.trim();
        
        // Auto-generate if description, meta fields are empty
        if (!description && !metaTitle && !metaDescription && !metaKeywords) {
            console.log(`🔄 Regenerating content for updated category: ${name.trim()}`);
            const generated = await generateDescriptionWithGemini(name.trim());
            category.description = generated.description;
            category.metaTitle = generated.metaTitle;
            category.metaDescription = generated.metaDescription;
            
            if (generated.metaKeywords.length > 0) {
                category.metaKeywords = generated.metaKeywords;
            }
        }
        
        const slug = slugify(name.trim(), { lower: true, strict: true });
        let finalSlug = slug;
        let counter = 1;
        while (await Category.findOne({ slug: finalSlug, _id: { $ne: id } })) {
            finalSlug = `${slug}-${counter}`;
            counter++;
        }
        category.slug = finalSlug;
    }

    // Update other fields (if provided, they override auto-generated content)
    if (description !== undefined && description.trim()) {
        category.description = description;
    }
    if (parent !== undefined) category.parent = parent === 'null' ? null : parent;
    if (status) category.status = status;
    if (featured !== undefined) category.featured = featured === 'true' || featured === true;
    if (metaTitle !== undefined && metaTitle.trim()) {
        category.metaTitle = metaTitle;
    }
    if (metaDescription !== undefined && metaDescription.trim()) {
        category.metaDescription = metaDescription;
    }
    if (displayOrder !== undefined) category.displayOrder = parseInt(displayOrder) || 0;

    if (metaKeywords !== undefined) {
        if (Array.isArray(metaKeywords)) {
            category.metaKeywords = metaKeywords;
        } else if (typeof metaKeywords === 'string' && metaKeywords.trim()) {
            category.metaKeywords = metaKeywords.split(',').map(k => k.trim()).filter(Boolean);
        }
    }

    await category.save();

    reply.status(200).send({
        success: true,
        message: 'Category updated successfully',
        data: category
    });
};

// ✅ 6. DELETE CATEGORY
export const deleteCategory = async (req, reply) => {
    const { id } = req.params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
        throw new ValidationError('Invalid category ID', {
            field: 'id',
            received: id
        });
    }

    const category = await Category.findById(id);
    if (!category) {
        throw new NotFoundError('Category', { id });
    }

    const subcategories = await Category.find({ parent: id });
    if (subcategories.length > 0) {
        throw new BusinessLogicError(
            `Cannot delete category with ${subcategories.length} subcategory(s)`,
            {
                subcategoriesCount: subcategories.length,
                subcategories: subcategories.map(s => s.name)
            }
        );
    }

    const productsCount = await Product.countDocuments({ category: id });
    if (productsCount > 0) {
        throw new BusinessLogicError(
            `Cannot delete category with ${productsCount} product(s)`,
            {
                productsCount: productsCount,
                categoryId: id
            }
        );
    }

    if (category.image) {
        await deleteFile(category.image);
    }

    await Category.findByIdAndDelete(id);

    reply.status(200).send({
        success: true,
        message: 'Category deleted successfully'
    });
};

// ✅ 7. GET CATEGORIES TREE
export const getCategoriesTree = async (req, reply) => {
    const categories = await Category.find({ status: 'active' }).sort('displayOrder name');
    
    const categoryMap = {};
    const roots = [];

    categories.forEach(category => {
        categoryMap[category._id] = { ...category.toObject(), children: [] };
    });

    categories.forEach(category => {
        if (category.parent && categoryMap[category.parent]) {
            categoryMap[category.parent].children.push(categoryMap[category._id]);
        } else {
            roots.push(categoryMap[category._id]);
        }
    });

    reply.status(200).send({
        success: true,
        data: roots
    });
};

// ✅ 8. GET CATEGORY PRODUCTS
export const getCategoryProducts = async (req, reply) => {
    const { id } = req.params;
    const { page = 1, limit = 12, sortBy = 'createdAt', sortOrder = 'desc' } = req.query;

    if (!mongoose.Types.ObjectId.isValid(id)) {
        throw new ValidationError('Invalid category ID', {
            field: 'id',
            received: id
        });
    }

    const category = await Category.findById(id);
    if (!category) {
        throw new NotFoundError('Category', { id });
    }

    const subcategories = await Category.find({ parent: id, status: 'active' });
    const categoryIds = [id, ...subcategories.map(sub => sub._id)];

    const skip = (parseInt(page) - 1) * parseInt(limit);
    const sortConfig = { [sortBy]: sortOrder === 'desc' ? -1 : 1 };

    const [products, totalCount] = await Promise.all([
        Product.find({ category: { $in: categoryIds }, status: 'active' })
            .populate('category', 'name slug')
            .sort(sortConfig)
            .skip(skip)
            .limit(parseInt(limit))
            .lean(),
        Product.countDocuments({ category: { $in: categoryIds }, status: 'active' })
    ]);

    reply.status(200).send({
        success: true,
        category: { _id: category._id, name: category.name, slug: category.slug },
        data: products,
        pagination: {
            currentPage: parseInt(page),
            totalPages: Math.ceil(totalCount / parseInt(limit)),
            totalProducts: totalCount,
            hasNext: skip + products.length < totalCount,
            hasPrev: parseInt(page) > 1
        }
    });
};